import json
from pathlib import Path

import pytest

from werktools.catalog import CatalogCard
from werktools.hub.export_rules import (
    export_hook_catalog,
    export_rules,
    render_claude_md,
    render_cursor_mdc,
    render_skill_md,
)
from werktools.hub.ledger import recent_events

FIX = Path(__file__).parent / "fixtures"
AGENTS = FIX / "agents_base.md"
SKILLS = FIX / "skills"


def test_render_claude_md_golden():
    assert render_claude_md("./AGENTS.md") == (
        "# CLAUDE.md\n\n"
        "<!-- Auto-generated by werktools hub export-rules. Edit AGENTS.md instead. -->\n\n"
        "@./AGENTS.md\n\n"
        "<!-- Hooks are host-specific; WERKHub catalogs them, it does not execute them. -->\n"
    )


def test_render_skill_md_frontmatter():
    card = CatalogCard.from_dict({"card_id": "x", "title": "X", "tags": ["a"], "risk": "read", "profiles": ["*"], "summary": "does x"})
    text = render_skill_md(card)
    # agentskills.io open standard: REQUIRED frontmatter is exactly name + description
    assert "name: x" in text
    assert "description:" in text and "does x" in text
    # werktools extras moved UNDER metadata (not top-level required fields)
    assert "metadata:" in text
    assert "werk_risk:" in text and "read" in text
    assert "werk_id:" in text


def test_render_skill_md_name_is_spec_conformant():
    # uppercase / spaces / consecutive separators -> lowercase, single-hyphen, trimmed
    card = CatalogCard.from_dict({"card_id": "My  Cool__Skill!!", "summary": "s"})
    text = render_skill_md(card)
    assert "name: my-cool-skill" in text


def test_render_cursor_mdc_requires_exactly_one():
    with pytest.raises(ValueError):
        render_cursor_mdc()
    with pytest.raises(ValueError):
        render_cursor_mdc(card=CatalogCard.from_dict({"card_id": "x"}), agents_md_text="y")
    text = render_cursor_mdc(agents_md_text="rules here")
    assert "alwaysApply: true" in text
    assert "rules here" in text


def test_claude_host_writes_agents_and_claude(tmp_path):
    manifest = export_rules(AGENTS, SKILLS, tmp_path, "claude-reviewer", "claude", ledger_path=tmp_path / "l.jsonl")
    assert (tmp_path / "AGENTS.md").exists()
    assert (tmp_path / "CLAUDE.md").exists()
    claude = (tmp_path / "CLAUDE.md").read_text(encoding="utf-8")
    assert "@./AGENTS.md" in claude
    # skill filter: review-policy visible, admin-deploy not (admin-only)
    agents = (tmp_path / "AGENTS.md").read_text(encoding="utf-8")
    assert "review-policy" in agents
    assert "admin-deploy" not in agents
    assert manifest.skill_count == 1


def test_admin_sees_both_skills(tmp_path):
    manifest = export_rules(AGENTS, SKILLS, tmp_path, "human-admin", "claude", ledger_path=tmp_path / "l.jsonl")
    assert manifest.skill_count == 2


def test_codex_writes_agents_only(tmp_path):
    export_rules(AGENTS, SKILLS, tmp_path, "human-admin", "codex", ledger_path=tmp_path / "l.jsonl")
    assert (tmp_path / "AGENTS.md").exists()
    assert not (tmp_path / "CLAUDE.md").exists()
    assert not (tmp_path / ".cursor").exists()


def test_cursor_writes_mdc_no_claude(tmp_path):
    manifest = export_rules(AGENTS, SKILLS, tmp_path, "human-admin", "cursor", ledger_path=tmp_path / "l.jsonl")
    assert (tmp_path / ".cursor" / "rules" / "agents-rules.mdc").exists()
    assert not (tmp_path / "CLAUDE.md").exists()
    assert manifest.cursor_rules


def test_all_host_is_union(tmp_path):
    export_rules(AGENTS, SKILLS, tmp_path, "human-admin", "all", ledger_path=tmp_path / "l.jsonl")
    assert (tmp_path / "AGENTS.md").exists()
    assert (tmp_path / "CLAUDE.md").exists()
    assert (tmp_path / ".cursor" / "rules").exists()
    assert list((tmp_path / "skills").glob("*/SKILL.md"))


def test_skill_export_is_agentskills_conformant(tmp_path):
    """Exported skills follow agentskills.io: <name>/SKILL.md with name == dir name,
    a non-empty required description, and werktools extras under metadata."""
    import re as _re

    export_rules(AGENTS, SKILLS, tmp_path, "human-admin", "claude", ledger_path=tmp_path / "l.jsonl")
    skill_files = list((tmp_path / "skills").glob("*/SKILL.md"))
    assert skill_files, "expected <name>/SKILL.md directories"
    for sf in skill_files:
        text = sf.read_text(encoding="utf-8")
        dir_name = sf.parent.name
        assert f"name: {dir_name}" in text, f"name must match dir {dir_name!r}"
        m = _re.search(r"^description:\s*(.+)$", text, _re.MULTILINE)
        assert m and m.group(1).strip() not in ("", '""'), "description required + non-empty"
        assert "metadata:" in text


def test_hook_catalog_empty_then_populated(tmp_path):
    plain = CatalogCard.from_dict({"card_id": "p"})
    assert export_hook_catalog([plain], tmp_path / "h.json") == []
    hooked = CatalogCard.from_dict(
        {"card_id": "h", "metadata": {"hooks": [{"event": "before_shell", "host": "claude", "description": "block"}]}}
    )
    entries = export_hook_catalog([hooked], tmp_path / "h.json")
    assert entries[0]["hook_event"] == "before_shell"
    assert (tmp_path / "h.json").exists()


def test_ledger_records_rules_exported(tmp_path):
    export_rules(AGENTS, SKILLS, tmp_path, "claude-reviewer", "claude", ledger_path=tmp_path / "l.jsonl")
    events = recent_events(tmp_path / "l.jsonl", limit=5)
    assert events[-1]["payload"]["type"] == "rules.exported"
    assert events[-1]["payload"]["host"] == "claude"


def test_unknown_host_and_missing_source(tmp_path):
    with pytest.raises(ValueError):
        export_rules(AGENTS, SKILLS, tmp_path, "p", "emacs", ledger_path=tmp_path / "l.jsonl")
    with pytest.raises(FileNotFoundError):
        export_rules(tmp_path / "nope.md", SKILLS, tmp_path, "p", "claude", ledger_path=tmp_path / "l.jsonl")


def test_idempotent_byte_identical(tmp_path):
    export_rules(AGENTS, SKILLS, tmp_path, "claude-reviewer", "claude", ledger_path=tmp_path / "l.jsonl")
    first = (tmp_path / "AGENTS.md").read_bytes()
    export_rules(AGENTS, SKILLS, tmp_path, "claude-reviewer", "claude", ledger_path=tmp_path / "l.jsonl")
    assert (tmp_path / "AGENTS.md").read_bytes() == first


def test_cli_export_rules(tmp_path, capsys):
    from werktools.cli import main
    from werktools.hub.registry import default_config

    config = tmp_path / "hub.json"
    body = default_config().to_dict()
    body["ledger_path"] = str(tmp_path / "hub-ledger.jsonl")
    config.write_text(json.dumps(body), encoding="utf-8")
    out = tmp_path / "export"

    code = main(
        ["--config", str(config), "hub", "export-rules", "--agents-md", str(AGENTS),
         "--skills-dir", str(SKILLS), "--out", str(out), "--profile", "claude-reviewer", "--host", "claude"]
    )
    assert code == 0
    assert "Export complete:" in capsys.readouterr().out

    bad = main(
        ["--config", str(config), "hub", "export-rules", "--agents-md", str(AGENTS),
         "--skills-dir", str(SKILLS), "--out", str(out), "--host", "emacs"]
    )
    assert bad == 1
