"""Export per-host rule/skill files from one authoritative AGENTS.md.

AGENTS.md is the cross-vendor convergence point (read natively by Codex,
Cursor, Copilot, Gemini, Windsurf, Zed). Claude Code does not read it, so we
emit a CLAUDE.md that @imports it. Skills export as SKILL.md; Cursor gets
.mdc rules. Hooks are cataloged as static JSON, never executed.

Stdlib + werktools.catalog/hub.contracts/hub.ledger only — no FastMCP, no
hub.registry, no daemon. One-shot synchronous; everything ledgered.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ..catalog import CatalogCard, load_cards, visible_cards
from .ledger import record_event

SUPPORTED_HOSTS = ("claude", "codex", "cursor", "copilot", "gemini", "windsurf", "zed", "all")
_CLAUDE_MD = (
    "# CLAUDE.md\n\n"
    "<!-- Auto-generated by werktools hub export-rules. Edit AGENTS.md instead. -->\n\n"
    "@{rel}\n\n"
    "<!-- Hooks are host-specific; WERKHub catalogs them, it does not execute them. -->\n"
)
_SAFE_STEM = re.compile(r"[^A-Za-z0-9_-]+")


@dataclass(frozen=True)
class ExportManifest:
    profile_id: str
    host: str
    agents_md_path: str
    claude_md_path: str | None
    skill_dirs: tuple[str, ...]
    cursor_rules: tuple[str, ...]
    hook_catalog_path: str | None
    skill_count: int
    hook_count: int

    def to_dict(self) -> dict[str, Any]:
        return {
            "profile_id": self.profile_id,
            "host": self.host,
            "agents_md_path": self.agents_md_path,
            "claude_md_path": self.claude_md_path,
            "skill_dirs": list(self.skill_dirs),
            "cursor_rules": list(self.cursor_rules),
            "hook_catalog_path": self.hook_catalog_path,
            "skill_count": self.skill_count,
            "hook_count": self.hook_count,
        }


def render_agents_md(source_text: str, profile_id: str, skill_cards: list[CatalogCard]) -> str:
    lines = [source_text.rstrip(), "", "## Skill Library", "", f"Skills visible to profile `{profile_id}`:", ""]
    if skill_cards:
        lines.append("| Skill | Risk | Summary |")
        lines.append("| --- | --- | --- |")
        for card in skill_cards:
            lines.append(f"| `{card.card_id}` | {card.risk} | {card.summary} |")
    else:
        lines.append("- none")
    return "\n".join(lines) + "\n"


def render_claude_md(agents_md_rel_path: str) -> str:
    return _CLAUDE_MD.format(rel=agents_md_rel_path)


def _q(value: str) -> str:
    """YAML-safe scalar — JSON double-quoted strings are valid YAML scalars."""
    return json.dumps(value, ensure_ascii=False)


def _skill_name(card_id: str) -> str:
    """A SKILL.md-spec name (agentskills.io): lowercase a-z0-9 + single hyphens,
    no leading/trailing/consecutive hyphens, <= 64 chars. Falls back to 'skill'."""
    slug = re.sub(r"[^a-z0-9]+", "-", card_id.lower())
    slug = re.sub(r"-{2,}", "-", slug).strip("-")
    return slug[:64].strip("-") or "skill"


def render_skill_md(card: CatalogCard) -> str:
    """Render a card as a SKILL.md conformant with the agentskills.io open standard.

    REQUIRED frontmatter is exactly ``name`` + ``description``; the werktools fields
    (id/title/tags/risk/profiles/source) live under the optional ``metadata`` map
    (string values) so strict cross-harness parsers (Codex, Cursor, Zed, Gemini, …)
    accept the file. ``name`` matches the skill's directory name (see export_rules).
    """
    name = _skill_name(card.card_id)
    description = (card.summary or card.title or card.card_id).replace("\n", " ").strip()[:1024]
    front = [
        "---",
        f"name: {name}",
        f"description: {_q(description or card.card_id)}",
        "metadata:",
        f"  werk_id: {_q(card.card_id)}",
        f"  werk_title: {_q(card.title)}",
        f"  werk_tags: {_q(', '.join(card.tags))}",
        f"  werk_risk: {_q(card.risk)}",
        f"  werk_profiles: {_q(', '.join(card.profiles))}",
        f"  werk_source: {_q(card.source)}",
        "---",
        "",
        card.summary,
        "",
        f"<!-- source: {card.source} -->",
        "",
    ]
    return "\n".join(front)


def render_cursor_mdc(card: CatalogCard | None = None, agents_md_text: str | None = None, rule_name: str = "rule") -> str:
    if (card is None) == (agents_md_text is None):
        raise ValueError("render_cursor_mdc requires exactly one of card or agents_md_text")
    if card is not None:
        description = card.title
        body = card.summary
    else:
        description = "Project rules from AGENTS.md"
        body = agents_md_text or ""
    return (
        "---\n"
        f"description: {description}\n"
        "globs: ['**/*']\n"
        "alwaysApply: true\n"
        "---\n\n"
        f"{body}\n"
    )


def export_hook_catalog(skill_cards: list[CatalogCard], output_path: Path) -> list[dict[str, Any]]:
    entries: list[dict[str, Any]] = []
    for card in skill_cards:
        hooks = card.metadata.get("hooks") if isinstance(card.metadata, dict) else None
        if not isinstance(hooks, list):
            continue
        for hook in hooks:
            if not isinstance(hook, dict):
                continue
            entries.append(
                {
                    "skill_id": card.card_id,
                    "hook_event": str(hook.get("event", "")),
                    "host": str(hook.get("host", "")),
                    "description": str(hook.get("description", "")),
                }
            )
    if entries:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(json.dumps(entries, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return entries


def _stem(card_id: str) -> str:
    return _SAFE_STEM.sub("-", card_id).strip("-") or "skill"


def export_rules(
    agents_md_source: str | Path,
    skills_dir: str | Path,
    output_dir: str | Path,
    profile_id: str,
    host: str,
    hub_config: Any = None,
    ledger_path: str | Path | None = None,
) -> ExportManifest:
    """Render AGENTS.md (+ per-host extras) for one profile into output_dir."""
    if host not in SUPPORTED_HOSTS:
        raise ValueError(f"unknown host {host!r}; known: {', '.join(SUPPORTED_HOSTS)}")
    source = Path(agents_md_source)
    if not source.exists():
        raise FileNotFoundError(f"AGENTS.md source not found: {source}")
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    cards = visible_cards(load_cards(skills_dir, kind="skill"), profile_id)
    agents_text = render_agents_md(source.read_text(encoding="utf-8"), profile_id, cards)
    agents_path = out / "AGENTS.md"
    agents_path.write_text(agents_text, encoding="utf-8")

    claude_path: str | None = None
    skill_dirs: list[str] = []
    cursor_rules: list[str] = []

    wants_claude = host in ("claude", "all")
    wants_cursor = host in ("cursor", "all")
    wants_skills = host in ("claude", "cursor", "all")

    if wants_claude:
        claude_file = out / "CLAUDE.md"
        claude_file.write_text(render_claude_md("./AGENTS.md"), encoding="utf-8")
        claude_path = str(claude_file)

    if wants_skills:
        skills_out = out / "skills"
        skills_out.mkdir(parents=True, exist_ok=True)
        for card in cards:
            # agentskills.io layout: one directory per skill, name == directory name.
            skill_dir = skills_out / _skill_name(card.card_id)
            skill_dir.mkdir(parents=True, exist_ok=True)
            (skill_dir / "SKILL.md").write_text(render_skill_md(card), encoding="utf-8")
        if cards:
            skill_dirs.append(str(skills_out))

    if wants_cursor:
        rules_dir = out / ".cursor" / "rules"
        rules_dir.mkdir(parents=True, exist_ok=True)
        agents_rule = rules_dir / "agents-rules.mdc"
        agents_rule.write_text(render_cursor_mdc(agents_md_text=agents_text, rule_name="agents-rules"), encoding="utf-8")
        cursor_rules.append(str(agents_rule))
        for card in cards:
            rule = rules_dir / f"{_stem(card.card_id)}.mdc"
            rule.write_text(render_cursor_mdc(card=card, rule_name=card.card_id), encoding="utf-8")
            cursor_rules.append(str(rule))

    hook_entries = export_hook_catalog(cards, out / "hook-catalog.json")
    hook_catalog_path = str(out / "hook-catalog.json") if hook_entries else None

    manifest = ExportManifest(
        profile_id=profile_id,
        host=host,
        agents_md_path=str(agents_path),
        claude_md_path=claude_path,
        skill_dirs=tuple(skill_dirs),
        cursor_rules=tuple(cursor_rules),
        hook_catalog_path=hook_catalog_path,
        skill_count=len(cards),
        hook_count=len(hook_entries),
    )

    ledger = ledger_path
    if ledger is None:
        ledger = (
            Path(hub_config.ledger_path)
            if hub_config is not None
            else Path.cwd() / ".werktools" / "hub-ledger.jsonl"
        )
    record_event(ledger, "rules.exported", manifest.to_dict())
    return manifest
